/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiExpensesRouteImport } from './routes/api/expenses'
import { Route as ApiSalariesRouteImport } from './routes/api/salaries'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExpensesRoute = ApiExpensesRouteImport.update({
  id: '/api/expenses',
  path: '/api/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSalariesRoute = ApiSalariesRouteImport.update({
  id: '/api/salaries',
  path: '/api/salaries',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/expenses': typeof ApiExpensesRoute
  '/api/salaries': typeof ApiSalariesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/expenses': typeof ApiExpensesRoute
  '/api/salaries': typeof ApiSalariesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/expenses': typeof ApiExpensesRoute
  '/api/salaries': typeof ApiSalariesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/expenses' | '/api/salaries'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/expenses' | '/api/salaries'
  id: '__root__' | '/' | '/api/expenses' | '/api/salaries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiExpensesRoute: typeof ApiExpensesRoute
  ApiSalariesRoute: typeof ApiSalariesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/expenses': {
      id: '/api/expenses'
      path: '/api/expenses'
      fullPath: '/api/expenses'
      preLoaderRoute: typeof ApiExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/salaries': {
      id: '/api/salaries'
      path: '/api/salaries'
      fullPath: '/api/salaries'
      preLoaderRoute: typeof ApiSalariesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiExpensesRoute: ApiExpensesRoute,
  ApiSalariesRoute: ApiSalariesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
